version: '3.3'

services:
  db:
    image: mysql:5.6
    restart: always
    container_name: airbnb_db
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ../data/db/:/var/lib/mysql
    ports:
      - '3306:3306'