default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 10
  username: root
  password: password
  host: 0.0.0.0
  port: 3306

development:
  <<: *default
  database: airbnb_replication_for_inteview_development

test:
  <<: *default
  database: airbnb_replication_for_inteview_test

production:
  <<: *default
  database: airbnb_replication_for_inteview_production
  username: <%= ENV['MYSQL_DATABASE_USERNAME'] %>
  password: <%= ENV['MYSQL_DATABASE_PASSWORD'] %>
